name: Terragrunt Apply

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch, adjust as needed

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Specify the US West region

      - name: Install Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.31.3/terragrunt_linux_amd64 -O /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Apply - Dev
        working-directory: dev
        run: |
          terragrunt init
          terragrunt apply -auto-approve

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Specify the US West region

      - name: Terragrunt Apply - Prod
        working-directory: prod
        run: |
          terragrunt init
          terragrunt apply -auto-approve
