name: Terraform Apply

on:
  push:
    branches:
      - main  # Modify as needed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Modify as needed

      - name: Install Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.31.3/terragrunt_linux_amd64 -O /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Apply - Dev
        run: cd myinfrastructure/dev && terragrunt apply -auto-approve

      - name: Terragrunt Apply - Prod
        run: cd myinfrastructure/prod && terragrunt apply -auto-approve

      # Add more steps as needed, such as testing, validation, and notifications.
